---
driver:
  name: vagrant
  network:
    - ['private_network', {ip: "172.168.21.5"}]

provisioner:
  name: chef_zero
  data_bags_path: /test/integration/nodes

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[consul::agent]
    attributes:
      consul:
        node:
          name: "consul-agent"
          bind_addr: "172.168.21.5"
        server:
          bindable_ips: 
            - "172.168.100.2"
            - "172.168.100.3"
            - "172.168.100.4"
