---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: /test/integration/nodes

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[consul::cluster]
    attributes:
